use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use tracing::{info, warn};

use crate::agent::{Agent, AgentError};
use crate::client::ConsoleClient;
use crate::types::{AgentConfig, AgentEvent, AgentTelemetry, WorkloadSpec};

/// A simulated satellite that replays pre-computed CAE event streams.
///
/// Instead of running real computations, it takes the event timeline
/// generated by the CAE simulator and replays events with realistic
/// timing (adjustable via `speed_multiplier`).
pub struct SimulatedSatellite {
    config: AgentConfig,
    client: ConsoleClient,
    speed_multiplier: f64,
    running: Arc<AtomicBool>,
}

impl SimulatedSatellite {
    /// Create a new simulated satellite.
    ///
    /// `speed_multiplier` controls replay speed:
    /// - 1.0 = real-time
    /// - 10.0 = 10x faster
    /// - 100.0 = 100x faster (default for demos)
    pub fn new(config: AgentConfig, speed_multiplier: f64) -> Result<Self, AgentError> {
        let client = ConsoleClient::new(config.clone())?;
        Ok(Self {
            config,
            client,
            speed_multiplier,
            running: Arc::new(AtomicBool::new(false)),
        })
    }

    /// Parse an ISO 8601 timestamp, returning None on failure.
    fn parse_timestamp(ts: &str) -> Option<DateTime<Utc>> {
        ts.parse::<DateTime<Utc>>().ok()
    }
}

#[async_trait]
impl Agent for SimulatedSatellite {
    async fn poll(&self) -> Result<Option<WorkloadSpec>, AgentError> {
        self.client.poll_workloads().await
    }

    async fn report_event(&self, event: &AgentEvent) -> Result<(), AgentError> {
        // In simulation mode, deployment_id comes from the workload context.
        // The CLI passes it via the event's job_id field mapping.
        // For direct execution, we extract it from the current workload.
        info!(
            event_type = %event.event_type,
            step_id = ?event.step_id,
            "Event: {}",
            event.event_type
        );
        Ok(())
    }

    async fn report_telemetry(&self, telemetry: &AgentTelemetry) -> Result<(), AgentError> {
        self.client.report_telemetry(telemetry).await
    }

    async fn execute(&self, workload: &WorkloadSpec) -> Result<(), AgentError> {
        let events = &workload.events;
        if events.is_empty() {
            return Err(AgentError::ExecutionError("No events in workload".into()));
        }

        info!(
            deployment_id = %workload.deployment_id,
            events_count = events.len(),
            speed = self.speed_multiplier,
            "Starting simulated execution"
        );

        let first_ts = Self::parse_timestamp(&events[0].timestamp);

        for (i, event) in events.iter().enumerate() {
            if !self.running.load(Ordering::Relaxed) {
                warn!("Agent stopped, aborting execution");
                return Err(AgentError::Stopped);
            }

            // Calculate delay based on time difference from previous event
            if i > 0 {
                if let (Some(prev_ts), Some(curr_ts)) = (
                    Self::parse_timestamp(&events[i - 1].timestamp),
                    Self::parse_timestamp(&event.timestamp),
                ) {
                    let delta = curr_ts
                        .signed_duration_since(prev_ts)
                        .num_milliseconds()
                        .max(0) as f64;
                    let adjusted_ms = delta / self.speed_multiplier;
                    if adjusted_ms > 1.0 {
                        tokio::time::sleep(std::time::Duration::from_millis(adjusted_ms as u64))
                            .await;
                    }
                }
            }

            // Report event to Console API
            self.client
                .report_event(&workload.deployment_id, event)
                .await
                .unwrap_or_else(|e| {
                    warn!(error = %e, "Failed to report event, continuing");
                });

            // Log locally
            let elapsed = first_ts
                .and_then(|ft| {
                    Self::parse_timestamp(&event.timestamp)
                        .map(|ct| ct.signed_duration_since(ft).num_seconds())
                })
                .unwrap_or(0);

            info!(
                "[T+{:>6}s] {} {}",
                elapsed,
                event.event_type,
                event.step_id.as_deref().unwrap_or("")
            );
        }

        info!(
            deployment_id = %workload.deployment_id,
            "Simulated execution complete"
        );
        Ok(())
    }

    async fn start(&self) -> Result<(), AgentError> {
        self.running.store(true, Ordering::Relaxed);
        info!(
            agent_id = %self.config.agent_id,
            api_url = %self.config.api_url,
            poll_interval = self.config.poll_interval_s,
            "Agent started"
        );

        while self.running.load(Ordering::Relaxed) {
            match self.poll().await {
                Ok(Some(workload)) => {
                    info!(
                        deployment_id = %workload.deployment_id,
                        "Received workload"
                    );
                    if let Err(e) = self.execute(&workload).await {
                        warn!(error = %e, "Workload execution failed");
                    }
                }
                Ok(None) => {
                    // No work available, wait and poll again
                }
                Err(e) => {
                    warn!(error = %e, "Poll failed, will retry");
                }
            }

            if self.running.load(Ordering::Relaxed) {
                tokio::time::sleep(std::time::Duration::from_secs(
                    self.config.poll_interval_s,
                ))
                .await;
            }
        }

        Ok(())
    }

    async fn stop(&self) -> Result<(), AgentError> {
        self.running.store(false, Ordering::Relaxed);
        info!("Agent stopped");
        Ok(())
    }
}
